[package]
name = "mylib"
version = "0.1.0"
# default is 'static', possible: 'dynamic', 'foreign' (requires 'exports' section)
type = "dynamic"
# command to run the script, executed always before building packages that depend on this one:
# {build_dir} is substituted with absolute path to e.g. "package_root/build/debug" directory
script_run = "python build_script.py {build_dir}"
# generated toml file to merge with this one, only 'exports', 'copy' sections are supported
# required to perform copy/link phase on changes
script_out = "{build_dir}/out_config.toml"

# custom compiler flags
[build-all]
c_flags = [""]
include_paths = [""]

# for generated code
sources = ['{build_dir}/out.c']

[build-linux]
link_libs = ["m", "pthreads"]
link_search_paths = [""]

# optional section, required for binary only foreign package
[exports-all]
# flags to pass to C compiler
c_flags = "tt tt"
# flags to pass to linker
link_flags = "a b"
# lib names without prefix/suffix
link_libs = ['a', 'b']
link_paths = ['path1', 'path2']
[exports-win32-debug]
link_libs = ['a_d']

# section specifies which files to copy to final product, for any build tag
[copy-all]
assets = ['assets/icon1.png', '{build_dir}/assets/en.txt']
# only if 'win32' build tag is set
[copy-win32]
dynamic_libs = ['libs/some_proprietary32.dll']
static_libs = ['libs/some_proprietary32.lib']
binaries = ['bin/tool.exe', 'bin/tool.sh']

[copy-win32-debug]
dynamic_libs = ['libs/some_proprietary32_d.dll']

# only if 'win64' tag is set
[copy-win64]
dynamic_libs = ['libs/some_proprietary64.dll']

[dependencies-win32]

win32_api = { src = "../win32_api" }

