[package]
name = "xlib"
version = "0.1.0"
type = "alien"

# expects deps-bin/lib/cmake/xlib/xlib-config.cmake file, which must export alias target

# expects xlib-install.cmake in the root, which is executed in cmake script mode.
# and xlib-uninstall.cmake

# that cmake file must do configure, build, install commands, like
# ['cmake', '-B', 'build', '-S', '.', '-DCMAKE_INSTALL_PREFIX', '../../deps-bin/']

# CMake variable XLIB_TAGS contains tags passed to this dependency.
