[package]
    name = "mylib"
    version = "0.1.0"
    is_library = true

    # declare custom tags
    tags = ['a', 'b', 'c']

    # default build configuration
    default_tags = ['a', 'b']

    # custom cmake module to include in the end of the generated CMakeLists.txt
    include_cmake = "cmake/generate_resources.cmake"

[[src]]
    # no tags, common sources
    sources = ['common1.c', 'utils.c']

[[src]]
    tags = ['a']
    sources = ['featurea.c']

[[src]]
    tags = ['b']
    sources = ['featureb.c']

[[src]]
    # used either when both 'a' and 'b' tags are set, or both 'a' and 'c'
    tags = [['a', 'b'], ['a', 'c']]
    sources = ['featurea.c', 'featurec.c']

# packages, required by this one:
[[deps]]
    # no tags, common featureset
    [deps.packages]
    printf = "0.1"
    math = "0.1"
    glmath = {version = "0.1", tags = ['no-double', 'sse2']}

[[deps]]
    tags = ['a']
    packages = { console = {version = "0.1", tags = ['with-logs']} }

[[deps]]
    tags = [['a', 'c'], ['a', 'b']]
    [deps.packages]
        console = {version = "0.1", tags = ['with-logs']}
        htmlreader = {version = "0.1"}

# compiler options:
[[opts]]
    tags = ['a']

    # pass -DV2_ENABLE_A=1 option to the compiler
    defines = ["V2_ENABLE_A=1"]

    # pass -lm
    link_libs = ['m']

[[opts]]
    tags = ['release']
    # optimize for size rather than speed
    opt_size = true
